### ISSUE TITLE
Release Spring Session Data Geode 2.1.0

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session-data-geode#9]
Spring Session Bean is scheduled for release on Oct 25th. For spring-session-data-geode 2.1.0 to be included, we need a the GA release by Oct 24th. If it is not available, we will need to roll back to the previous GA of spring-session-data-geode in order to ensure Spring Session Bean gets in Spring Boot

**Comment by jxblum** [comment]
Bits published to Maven Central...
https://search.maven.org/artifact/org.springframework.session/spring-session-data-geode/2.1.0.RELEASE/jar

https://search.maven.org/artifact/org.springframework.session/spring-session-data-gemfire/2.1.0.RELEASE/jar

Bits published to repo.spring.io/libs-release

https://repo.spring.io/libs-release/org/springframework/session/spring-session-data-geode/2.1.0.RELEASE/

https://repo.spring.io/libs-release/org/springframework/session/spring-session-data-gemfire/2.1.0.RELEASE/
